---
# Create docker-compose file, which could be used to run integration tests for this project
version: "3.8"
services:
  mail:
    image: tophfr/mailcatcher
    ports:
      - "80:80"
      - "25:25"
  redis:
    image: redis
    depends_on:
      - mail
    ports:
      - "6379:6379"